
version: '3.9'
services:
  backend:
    container_name: todolist-be
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: todolist-db
    environment:
      - POSTGRES_USER=kaito
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todolist
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kaito" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    container_name: todolist-fe
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env